import { createContext, useContext, useEffect, useState } from 'react'

const SiteContext = createContext(null)

const translations = {
  en: {
    home: 'Home',
    collections: 'Collections',
    about: 'About',
    requestQuotation: 'Request Quotation',
    requestQuotationShort: 'Quote',
    exploreCollections: 'Explore Collections',
    viewOurStory: 'View Our Story',
    luxuryTextiles: 'Luxury Home Fabrics & Wallpaper, Crafted for the Senses',
    homeAtelierDescription: "SA Studio was founded with a singular vision: to bring the world's most distinguished textiles to the discerning interiors of Damascus and the wider region. Each collection is personally selected for its technical mastery and aesthetic distinction.",
    yearsExcellence: 'Years of excellence',
    fabricReferences: 'Fabric references',
    damascusShowrooms: 'Damascus showrooms',
    newArrival: 'New Arrival',
    atelier: 'The Atelier',
    excellence: 'Three decades of curatorial excellence',
    learnMore: 'Learn More',
    materialLab: 'Material Lab',
    materialTitle: 'Touch, compare, and decide with confidence',
    materialDescription: 'Interactive previews and carefully curated material stories let your next design decision feel elevated before you even visit the showroom.',
    exploreFabric: 'Explore fabric',
    getInTouch: 'Get in touch',
    speakTeam: 'Speak directly with Our Team',
    chatWhatsApp: 'Chat on WhatsApp',
    ourStory: 'Our Story',
    curation: 'Curation',
    expertise: 'Expertise',
    service: 'Service',
    visitUs: 'Visit Us',
    showroom: 'Showroom',
    address: 'Address',
    hours: 'Hours',
    showroomHours: 'Saturday - Thursday, 11:00 AM - 7:00 PM',
    whatsapp: 'WhatsApp',
    viewMaps: 'View on Google Maps',
    browseCollections: 'Browse Collections',
    theCollections: 'The Collections',
    viewDetails: 'View Details',
    sort: 'Sort',
    view: 'View',
    grid: 'Grid',
    list: 'List',
    result: 'result',
    results: 'results',
    all: 'All',
    collection: 'Collection',
    contactUs: 'Contact Us',
    customOrders: 'custom orders',
    notFound: 'Fabric not found',
    backToCollections: 'Back to Collections',
    premiumTextile: 'Premium Luxury Textile - SA Studio Damascus',
    moreIn: 'More in',
    close: 'Close',
    requestSent: 'Request Sent',
    fullName: 'Full Name',
    phone: 'Phone / WhatsApp',
    projectDetails: 'Project Details',
    sendRequest: 'Send Request',
    yourName: 'Your name',
    footerRights: 'All rights reserved.',
    aboutName: 'Samer Aroudaki',
    aboutAndStudio: '& SA Studio',
    aboutYears: 'Twenty-one years of carefully sourced European textiles, designed to bring warmth, clarity and enduring character into the spaces people live in.',
    aboutQuote: 'Chosen not merely for beauty, but for the conversation it begins when brought into a space.',
    aboutFounder: 'Samer Aroudaki · Founder',
    aboutStoryHeading: 'Twenty-one years of personal curation.',
    aboutStoryOne: 'Founded in Damascus in 2005, SA Studio grew from a personal conviction: the most memorable interiors are built from materials chosen with care, not mass-produced for convenience.',
    aboutStoryTwo: "Samer Aroudaki began sourcing European textiles with a collector's eye, focusing on depth of texture, integrity of material and the emotional tone a fabric lends to a room.",
    aboutStoryThree: 'Today, the studio represents international maisons and supports architects, designers and private clients with a considered, tailored approach to luxury textiles.',
    aboutFoundation: 'Our foundation',
    trustedPartners: 'Trusted partners',
    visitOurShowroom: 'Visit our showroom',
    damascusShowroomHeading: 'Damascus showrooms',
    messageUs: 'Message us',
    curationText: 'Every reference is chosen by hand from Europe’s most respected textile houses, with a focus on character, performance and atmosphere.',
    precision: 'Precision',
    precisionText: 'We work across technical specifications, texture, durability and scale so each fabric feels as considered in application as it does in the room.',
    serviceText: 'From first sample to final installation, clients receive thoughtful guidance and a seamless, design-led process.',
    visitShowroom: 'Visit showroom',
    contactIntro: 'For inquiries, collaborations, press or custom requests, we would love to hear from you.',
    firstName: 'First Name',
    lastName: 'Last Name',
    email: 'Email',
    subject: 'Subject',
    yourMessage: 'Your message',
    thankYouContact: 'Thank you for reaching out.',
    contactFollowUp: 'Our team will be in touch shortly.',
    visitDamascus: 'Visit us in Damascus',
    viewGoogleMaps: 'View on Google Maps',
    seeMoreCollections: 'See more collections',
    studioEdit: 'The SA Studio edit',
    materialsRoom: 'Materials that make a room feel like yours.',
    collectionIntro: 'A considered edit of exceptional fabrics and materials for interiors with depth, character, and a distinct sense of place. Explore each collection by touch, texture, and origin.',
    noCollections: 'No collections are available yet.',
    allCategories: 'All',
    wallpaper: 'Wallpaper',
    upholstery: 'Upholstery',
    fabric: 'Fabric',
    sortAZ: 'A-Z',
    sortZA: 'Z-A',
    fabricNotFound: 'Fabric not found',
    backCollections: 'Back to Collections',
    requestFabricQuote: 'Request a Quotation',
    showroomLabel: 'Showroom',
    moreInCollection: 'More in',
    dashboard: 'Dashboard',
    fabricManagement: 'Fabric Management',
    fabricsList: 'Fabrics List',
    addNewFabric: 'Add New Fabric',
    searchFabrics: 'Search fabrics by name, collection, or category...',
    loadingFabrics: 'Loading fabrics...',
    noFabricsFound: 'No fabrics found',
    addFirstFabric: 'Add Your First Fabric',
    edit: 'Edit',
    delete: 'Delete',
    deleteConfirm: 'Are you sure you want to delete this fabric? This action cannot be undone.',
    yesDelete: 'Yes, Delete',
    cancel: 'Cancel',
    privateArea: 'Private area',
    adminSignIn: 'Admin sign in',
    password: 'Password',
    checkingAccess: 'Checking access...',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    signOut: 'Sign out',
    unableToSignIn: 'Unable to sign in with those details.',
    language: 'العربية',
    themeLight: 'Light',
    themeDark: 'Dark',
  },
  ar: {
    home: 'الرئيسية',
    collections: 'المجموعات',
    about: 'من نحن',
    requestQuotation: 'طلب عرض سعر',
    requestQuotationShort: 'طلب',
    exploreCollections: 'استكشف المجموعات',
    viewOurStory: 'اكتشف قصتنا',
    luxuryTextiles: 'أقمشة وورق جدران فاخر للمنزل، صُنع للحواس',
    homeAtelierDescription: 'تأسس استوديو SA برؤية واضحة: تقديم أرقى المنسوجات إلى المساحات الداخلية الراقية في دمشق والمنطقة. نختار كل مجموعة بعناية لما تتميز به من إتقان تقني وجمال مميز.',
    yearsExcellence: 'عاماً من التميز',
    fabricReferences: 'مرجعاً من الأقمشة',
    damascusShowrooms: 'صالتا عرض في دمشق',
    newArrival: 'وصل حديثاً',
    atelier: 'المشغل',
    excellence: 'ثلاثة عقود من التميز في الاختيار',
    learnMore: 'اعرف المزيد',
    materialLab: 'مختبر المواد',
    materialTitle: 'المس، قارن، واتخذ قرارك بثقة',
    materialDescription: 'تمنحك المعاينات التفاعلية وقصص المواد المختارة بعناية رؤية راقية لقرار التصميم قبل زيارة صالة العرض.',
    exploreFabric: 'استكشف القماش',
    getInTouch: 'تواصل معنا',
    speakTeam: 'تحدث مباشرة مع فريقنا',
    chatWhatsApp: 'تحدث عبر واتساب',
    ourStory: 'قصتنا',
    curation: 'اختيار دقيق',
    expertise: 'خبرة',
    service: 'خدمة',
    visitUs: 'زورونا',
    showroom: 'صالة العرض',
    address: 'العنوان',
    hours: 'ساعات العمل',
    showroomHours: 'السبت - الخميس، 11:00 صباحاً - 7:00 مساءً',
    whatsapp: 'واتساب',
    viewMaps: 'عرض الموقع على خرائط غوغل',
    browseCollections: 'تصفح المجموعات',
    theCollections: 'المجموعات',
    viewDetails: 'عرض التفاصيل',
    sort: 'ترتيب',
    view: 'عرض',
    grid: 'شبكة',
    list: 'قائمة',
    result: 'نتيجة',
    results: 'نتائج',
    all: 'الكل',
    collection: 'مجموعة',
    contactUs: 'تواصل معنا',
    customOrders: 'طلبات خاصة',
    notFound: 'القماش غير موجود',
    backToCollections: 'العودة إلى المجموعات',
    premiumTextile: 'منسوجات فاخرة - استوديو SA دمشق',
    moreIn: 'المزيد من',
    close: 'إغلاق',
    requestSent: 'تم إرسال الطلب',
    fullName: 'الاسم الكامل',
    phone: 'الهاتف / واتساب',
    projectDetails: 'تفاصيل المشروع',
    sendRequest: 'إرسال الطلب',
    yourName: 'اسمك',
    footerRights: 'جميع الحقوق محفوظة.',
    aboutName: 'Samer Aroudaki',
    aboutAndStudio: '& SA Studio',
    aboutYears: 'واحد وعشرون عاماً من المنسوجات الأوروبية المختارة بعناية، صُممت لتضفي الدفء والوضوح والشخصية الدائمة على المساحات التي نعيش فيها.',
    aboutQuote: 'لا تُختار لجمالها فحسب، بل للحوار الذي تبدأه حين تدخل إلى المكان.',
    aboutFounder: 'سمر عرودكي · المؤسس',
    aboutStoryHeading: 'واحد وعشرون عاماً من الاختيار الشخصي.',
    aboutStoryOne: 'تأسس استوديو SA في دمشق عام 2005 انطلاقاً من قناعة شخصية: أجمل المساحات الداخلية تُبنى من مواد اختيرت بعناية، لا من منتجات مصنّعة بكميات كبيرة.',
    aboutStoryTwo: 'بدأ سمر عرودكي باختيار المنسوجات الأوروبية بعين جامع التحف، مع التركيز على عمق الملمس ونقاء المادة والنبرة العاطفية التي يضفيها القماش على المكان.',
    aboutStoryThree: 'يمثل الاستوديو اليوم دور أزياء عالمية ويدعم المهندسين والمصممين والعملاء من القطاع الخاص بنهج مدروس ومخصص في عالم المنسوجات الفاخرة.',
    aboutFoundation: 'أساسنا',
    trustedPartners: 'شركاؤنا الموثوقون',
    visitOurShowroom: 'زوروا صالة العرض',
    damascusShowroomHeading: 'صالات عرض دمشق',
    messageUs: 'راسلونا',
    curationText: 'نختار كل مرجع يدوياً من أرقى دور المنسوجات الأوروبية، مع التركيز على الشخصية والأداء والأجواء.',
    precision: 'دقة',
    precisionText: 'نعمل على المواصفات التقنية والملمس والمتانة والمقياس، ليكون كل قماش مدروساً في تطبيقه كما هو في المكان.',
    serviceText: 'من العينة الأولى إلى التركيب النهائي، يحصل العملاء على إرشاد مدروس وعملية سلسة تقودها الرؤية التصميمية.',
    visitShowroom: 'زيارة صالة العرض',
    contactIntro: 'للاستفسارات والتعاون والطلبات الصحفية أو الطلبات الخاصة، يسعدنا أن نسمع منكم.',
    firstName: 'الاسم الأول',
    lastName: 'اسم العائلة',
    email: 'البريد الإلكتروني',
    subject: 'الموضوع',
    yourMessage: 'رسالتك',
    thankYouContact: 'شكراً لتواصلكم معنا.',
    contactFollowUp: 'سيتواصل فريقنا معكم قريباً.',
    visitDamascus: 'زورونا في دمشق',
    viewGoogleMaps: 'عرض على خرائط Google',
    seeMoreCollections: 'اكتشف المزيد من المجموعات',
    studioEdit: 'مختارات استوديو SA',
    materialsRoom: 'مواد تجعل المكان يشبهك.',
    collectionIntro: 'مختارات مدروسة من الأقمشة والمواد الاستثنائية لمساحات داخلية غنية بالشخصية والعمق. استكشفوا كل مجموعة عبر الملمس والمنشأ.',
    noCollections: 'لا تتوفر مجموعات بعد.',
    allCategories: 'الكل',
    wallpaper: 'ورق جدران',
    upholstery: 'تنجيد',
    fabric: 'قماش',
    sortAZ: 'أ-ي',
    sortZA: 'ي-أ',
    fabricNotFound: 'القماش غير موجود',
    backCollections: 'العودة إلى المجموعات',
    requestFabricQuote: 'طلب عرض سعر',
    showroomLabel: 'صالة العرض',
    moreInCollection: 'المزيد من',
    dashboard: 'لوحة التحكم',
    fabricManagement: 'إدارة الأقمشة',
    fabricsList: 'قائمة الأقمشة',
    addNewFabric: 'إضافة قماش جديد',
    searchFabrics: 'ابحث بالاسم أو المجموعة أو الفئة...',
    loadingFabrics: 'جارٍ تحميل الأقمشة...',
    noFabricsFound: 'لم يتم العثور على أقمشة',
    addFirstFabric: 'أضف أول قماش',
    edit: 'تعديل',
    delete: 'حذف',
    deleteConfirm: 'هل أنت متأكد من حذف هذا القماش؟ لا يمكن التراجع عن هذا الإجراء.',
    yesDelete: 'نعم، احذف',
    cancel: 'إلغاء',
    privateArea: 'منطقة خاصة',
    adminSignIn: 'تسجيل دخول الإدارة',
    password: 'كلمة المرور',
    checkingAccess: 'جارٍ التحقق من الوصول...',
    signIn: 'تسجيل الدخول',
    signingIn: 'جارٍ تسجيل الدخول...',
    signOut: 'تسجيل الخروج',
    unableToSignIn: 'تعذر تسجيل الدخول بهذه البيانات.',
    language: 'English',
    themeLight: 'فاتح',
    themeDark: 'داكن',
  },
}

export function SiteProvider({ children }) {
  const [theme, setTheme] = useState(() => localStorage.getItem('sa-theme') || 'dark')
  const [language, setLanguage] = useState(() => localStorage.getItem('sa-language') || 'en')

  useEffect(() => {
    document.documentElement.dataset.theme = theme
    document.documentElement.style.colorScheme = theme
    localStorage.setItem('sa-theme', theme)
  }, [theme])

  useEffect(() => {
    document.documentElement.lang = language
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr'
    localStorage.setItem('sa-language', language)
  }, [language])

  const value = {
    theme,
    language,
    toggleTheme: () => setTheme((current) => current === 'light' ? 'dark' : 'light'),
    toggleLanguage: () => setLanguage((current) => current === 'en' ? 'ar' : 'en'),
    t: (key) => translations[language][key] || translations.en[key] || key,
  }

  return <SiteContext.Provider value={value}>{children}</SiteContext.Provider>
}

// eslint-disable-next-line react-refresh/only-export-components
export function useSite() {
  return useContext(SiteContext)
}
