alter table public.fabrics
  add column if not exists categories jsonb not null default '[]'::jsonb;

create table if not exists public.fabric_colors (
  id bigint generated by default as identity primary key,
  fabric_id text not null references public.fabrics(id) on delete cascade,
  color_name text not null,
  image text not null,
  sort_order integer not null default 0
);

alter table public.fabric_colors enable row level security;

drop policy if exists "Fabric colors are publicly readable" on public.fabric_colors;
create policy "Fabric colors are publicly readable"
on public.fabric_colors for select
to anon, authenticated
using (true);

drop policy if exists "Admins can manage fabric colors" on public.fabric_colors;
create policy "Admins can manage fabric colors"
on public.fabric_colors for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create index if not exists fabrics_collection_idx on public.fabrics (collection);
create index if not exists fabrics_reference_idx on public.fabrics (reference);
create index if not exists fabrics_categories_gin_idx on public.fabrics using gin (categories);
create index if not exists fabric_colors_fabric_id_sort_idx on public.fabric_colors (fabric_id, sort_order);
